/* tslint:disable */
/* eslint-disable */
/**
 * Notes API
 * API for managing notes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNote400Response
 */
export interface CreateNote400Response {
    /**
     * 
     * @type {string}
     * @memberof CreateNote400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CreateNote400Response interface.
 */
export function instanceOfCreateNote400Response(value: object): boolean {
    return true;
}

export function CreateNote400ResponseFromJSON(json: any): CreateNote400Response {
    return CreateNote400ResponseFromJSONTyped(json, false);
}

export function CreateNote400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNote400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateNote400ResponseToJSON(value?: CreateNote400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

