/* tslint:disable */
/* eslint-disable */
/**
 * Notes API
 * API for managing notes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNoteRequest
 */
export interface CreateNoteRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNoteRequest
     */
    note: string;
}

/**
 * Check if a given object implements the CreateNoteRequest interface.
 */
export function instanceOfCreateNoteRequest(value: object): boolean {
    if (!('note' in value)) return false;
    return true;
}

export function CreateNoteRequestFromJSON(json: any): CreateNoteRequest {
    return CreateNoteRequestFromJSONTyped(json, false);
}

export function CreateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'],
    };
}

export function CreateNoteRequestToJSON(value?: CreateNoteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'note': value['note'],
    };
}

